
services:
  backend:
    build:
      context: .
    container_name: django-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
